package:
  name: vibes
  version: "0.2.2"

source:
  fn: vibes-0.2.2.tar.gz
  url: https://pypi.python.org/packages/20/3a/c19179d02310793aae928682a6435f97fe57e892f057048f1624b3675474/vibes-0.2.2.tar.gz
  md5: 560b1e8e5e7fad97a731c2b6f576bf17
#  patches:
   # List any patch files here
   # - fix.patch

#build:
  #noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - vibes = vibes:main
    #
    # Would create an entry point called vibes that calls vibes.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - vibes

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://enstabretagnerobotics.github.io/VIBES/
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'python Api for VIbes (VIsualizer for Intervals and Boxes)'
  license_family: GPL3
extra:
  recipe-maintainers:
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - BenEnsta <ben.ensta@gmail.com>
# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
